apiVersion: v2
name: helm-cert-manager
version: 1.0.0
appVersion: 1.23.0
description: A Helm chart wrapper for keycloak

dependencies:
  - name: keycloak
    version: "24.2.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: keycloak.enabled
