apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pgweb-cert
spec:
  secretName: pgweb-cert
  dnsNames:
    - {{ .Values.domain }}
  issuerRef:
    name: lets-encrypt-issuer-prod
    kind: ClusterIssuer
    group: cert-manager.io
