apiVersion: v2
name: helm-discord-alm
description: A Helm chart for Discord ALM

type: application

version: 1.0.0

appVersion: "1.0"

dependencies:
  - name: "generic-app"
    alias: discord-alm
    condition: discord-alm.enabled
    repository: "https://charts.visonneau.fr/"
    version: "0.0.14"
