version: '3'
volumes:
  k3s-server: {}
  k3s-agent: {}
services:
  server:
    hostname: k3s-master-1
    restart: always
    image: "rancher/k3s:${K3S_VERSION}"
    command:
    - server
    - --disable=traefik
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K3S_TOKEN=secret
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
      - .:/output
  
      - ./addons/initial-secrets.yaml:/var/lib/rancher/k3s/server/manifests/initial-secrets.yaml
      - ./addons/addons-argocd.yaml:/var/lib/rancher/k3s/server/manifests/addons-argocd.yaml
      - ./addons/addons-ingress.yaml:/var/lib/rancher/k3s/server/manifests/addons-ingress.yaml
      - ./addons/addons-external-secret.yaml:/var/lib/rancher/k3s/server/manifests/addons-external-secret.yaml
      - ./addons/addons-cert-manager.yaml:/var/lib/rancher/k3s/server/manifests/addons-cert-manager.yaml
  
      - k3s-server:/var/lib/rancher/k3s
    ports:
    - 6443:6443 # For kubectl
    - 443:32443
    - 80:32080 # For Let's Encrypt 
    logging:
      driver: "json-file"
      options: 
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  agent:
    hostname: k3s-worker-1
    restart: always
    image: "rancher/k3s:${K3S_VERSION}"
    command:
    - agent
    tmpfs:
    - /run
    - /var/run
    privileged: true
    volumes:
      - k3s-agent:/etc/rancher/node
      - ${STORAGE_DIR}:/var/lib/rancher/k3s/storage
    environment:
    - K3S_URL=https://server:6443
    - K3S_TOKEN=secret
    logging:
      driver: "json-file"
      options: 
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
