apiVersion: v2
name: helm-gatus 
version: 1.0.0
appVersion: 1.23.0
description: A Helm chart wrapper for Minio

dependencies:
  - name: "minio"
    alias: minio
    condition: minio.enabled
    repository: "https://charts.bitnami.com/bitnami"
    version: "17.0.21"
