---
domain: minio-console.otep.triple-t.co

minio:
  enabled: true
  nameOverride: minio
  image:
    registry: docker.io
    repository: bitnamilegacy/minio

  console:
    image:
      registry: docker.io
      repository: bitnamilegacy/minio-object-browser

  auth:
    existingSecret: minio-credentials
    rootUserSecretKey: MINIO_ROOT_USER
    rootPasswordSecretKey: MINIO_ROOT_PASSWORD
  
  persistence:
    enabled: true
    storageClass: "local-path"
    size: 50Gi