---
domain: minio-console.otep.triple-t.co

minio:
  enabled: true
  nameOverride: minio
  image:
    registry: docker.io
    repository: bitnamilegacy/minio
  console:
    image:
      registry: docker.io
      repository: bitnamilegacy/minio-object-browser
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hostname: minio-console.otep.triple-t.co