apiVersion: v2
name: helm-superset
version: 1.0.0
appVersion: 1.23.0
description: A Helm chart wrapper for Superset

dependencies:
  - name: "superset"
    alias: superset
    condition: superset.enabled
    repository: "http://apache.github.io/superset/"
    version: "0.15.0"
