apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nifi-credentials
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: nifi-credentials       # name of the k8s Secret to be created
  data:
  - secretKey: username
    remoteRef:
      key: initial-secret
      property: GRAFANA_USER

  - secretKey: password
    remoteRef:
      key: initial-secret
      property: GRAFANA_PASSWORD
