apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-alm-credentials
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: discord-alm-credentials  # name of the k8s Secret to be created
  data:
  - secretKey: DISCORD_WEBHOOK
    remoteRef:
      key: initial-secret
      property: DISCORD_WEBHOOK

