apiVersion: v2
name: helm-gatus 
version: 1.0.0
appVersion: 1.23.0
description: A Helm chart wrapper for PgWeb 

dependencies:
  - name: "pgweb"
    alias: pgweb
    condition: pgweb.enabled
    repository: "https://charts.ectobit.com"
    version: "0.1.9"
