apiVersion: v2
name: helm-loki-stack
version: 1.0.0
appVersion: 1.23.0
description: A Helm chart wrapper for Loki

dependencies:
  - name: loki-stack
    version: "2.10.3"
    repository: "https://grafana.github.io/helm-charts"
    condition: loki-stack.enabled
