apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-credentials
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: minio-credentials  # name of the k8s Secret to be created
  data:
  - secretKey: MINIO_ROOT_USER
    remoteRef:
      key: initial-secret
      property: KEYCLOAK_USER

  - secretKey: MINIO_ROOT_PASSWORD
    remoteRef:
      key: initial-secret
      property: KEYCLOAK_PASSWORD
