apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-console-cert
spec:
  secretName: minio-console-cert
  dnsNames:
    - {{ .Values.domainConsole }}
  issuerRef:
    name: lets-encrypt-issuer-prod
    kind: ClusterIssuer
    group: cert-manager.io
