apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-credentials
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: grafana-credentials       # name of the k8s Secret to be created
  data:
  - secretKey: GRAFANA_USER
    remoteRef:
      key: initial-secret
      property: GRAFANA_USER

  - secretKey: GRAFANA_PASSWORD
    remoteRef:
      key: initial-secret
      property: GRAFANA_PASSWORD
