apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-loki-sso
spec:
  refreshInterval: 10m0s       # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store     # name of the SecretStore (or kind specified)
  target:
    name: grafana-loki-sso  # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
  - secretKey: "SSO_CLIENT_SECRET"
    remoteRef:
      key: initial-secret
      version: latest
      property: SSO_CLIENT_SECRET
