apiVersion: v2
name: helm-redis
version: 1.0.0
appVersion: 1.23.0
description: A Helm chart wrapper for PostgreSQL

dependencies:
  ### pgSQL ###
  - name: "postgresql"
    alias: postgresql
    condition: postgresql.enabled
    repository: "https://charts.bitnami.com/bitnami"
    version: "15.2.9"
