apiVersion: v2
name: helm-nifi 
version: 1.0.0
appVersion: 1.23.0
description: A Helm chart wrapper for NifiKop

dependencies:
  - name: "nifikop"
    alias: nifikop
    condition: nifikop.enabled
    repository: "oci://ghcr.io/konpyutaika/helm-charts/nifikop"
    version: "0.15.0"
