apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nifi-ing
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  tls:
    - hosts:
      - {{ .Values.domain }}
      secretName: nifi-cert
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nifi-main-http
                port:
                  number: 8443
