---
kube-prometheus-stack:
  enabled: true
  fullnameOverride: prometheus

  prometheus-node-exporter: {}
    #hostRootFsMount:
    #  enabled: false
  
  #kubelet:
  #  enabled: false
  prometheus:
    prometheusSpec:
      retention: 60d
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi

  prometheusOperator:
    #kubeletService:
    #  enabled: false
    tls:
      enabled: false
    admissionWebhooks:
      enabled: false

  grafana:
    rbac:
      pspEnabled: false
    fullnameOverride: grafana-k8s
    #envFromSecret: google-oidc-secret
    admin:
      existingSecret: "grafana-credentials"
      userKey: GRAFANA_USER
      passwordKey: GRAFANA_PASSWORD

  alertmanager:
    # To allow AlertManger to be used globally (for all namespace)
    # https://github.com/sighupio/fury-kubernetes-monitoring/issues/132#issuecomment-1471854800
    alertmanagerSpec:
      alertmanagerConfigMatcherStrategy:
        type: None
