domain: grafana-k8s.otep.triple-t.co

kube-prometheus-stack:
  grafana:
    env:
      KC_ENDPOINT: "https://keycloak.otep.triple-t.co/realms/otep-prod/protocol/openid-connect"
    envFromSecrets:
      - name: grafana-k8s-keycloak
        optional: false
    grafana.ini:
      server:
        root_url: https://grafana-k8s.otep.triple-t.co
        domain: grafana-k8s.otep.triple-t.co
      auth.generic_oauth:
        enabled: true
        name: "SSO"
        client_id: "k8s-prod"
        client_secret: "r568Ookxqz0mUu9FJ5gTRgSoGBrcU1me"
        # client_secret: ${KC_CLIENT_SECRET}
        scopes: profile email openid roles
        auth_url: "${KC_ENDPOINT}/auth"
        token_url: "${KC_ENDPOINT}/token"
        api_url: "${KC_ENDPOINT}/userinfo"
        signout_redirect_url: https://grafana-k8s.otep.triple-t.co/login
        role_attribute_strict: true
        role_attribute_path: to_string('Editor')
        allow_assign_grafana_admin: true
        name_attribute_path: preferred_username