apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mb-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: mb-secret       # name of the k8s Secret to be created
  data:
  - secretKey: MB_PREMIUM_EMBEDDING_TOKEN
    remoteRef:
      key: initial-secret
      property: MB_PREMIUM_EMBEDDING_TOKEN
