apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metabase-ing
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
spec:
  tls:
    - hosts:
      - {{ .Values.domain }}
      secretName: metabase-cert
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: metabase-main
                port:
                  number: 80
