apiVersion: v1
kind: Service
metadata:
  name: pg-nodeport
spec:
  ports:
  - name: tcp
    port: 5432
    protocol: TCP
    targetPort: 5432
    nodePort: 32432
  selector:
    app.kubernetes.io/instance: postgresql-dev-main
    app.kubernetes.io/name: postgresql
  type: NodePort
