apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: postgres-secret       # name of the k8s Secret to be created
  data:
  - secretKey: adminPasswordKey
    remoteRef:
      key: initial-secret
      property: PG_PASSWORD_DEV # In the future we will use from another property
