apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-credentials
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: keycloak-credentials  # name of the k8s Secret to be created
  data:
  - secretKey: keycloak-admin-user
    remoteRef:
      key: initial-secret
      property: KEYCLOAK_USER

  - secretKey: keycloak-admin-password
    remoteRef:
      key: initial-secret
      property: KEYCLOAK_PASSWORD
