apiVersion: v2
name: helm-redis
version: 1.0.0
appVersion: 1.23.0
description: A Helm chart wrapper for Redis

dependencies:
  - name: "redis"
    alias: redis
    condition: redis.enabled
    repository: "https://charts.bitnami.com/bitnami"
    version: "18.13.0"
